---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cyonexla/public_html/
    - source /home/cyonexla/nodevenv/repositories/cyonex/24/bin/activate
    - npm ci
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R build/* $DEPLOYPATH
    - /bin/echo "<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
</IfModule>" > $DEPLOYPATH/.htaccess