---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cyonexla/public_html/

    # Step 1: Install dependencies
    - /usr/local/bin/npm ci

    # Step 2: Build the React app
    - /usr/local/bin/npm run build

    # Step 3: Remove old build
    - /bin/rm -rf $DEPLOYPATH/*

    # Step 4: Copy new build to public_html
    - /bin/cp -R build/* $DEPLOYPATH

    # Step 5: Add .htaccess for React Router support
    - /bin/echo "<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
</IfModule>" > $DEPLOYPATH/.htaccess
