---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cyonexla/public_html/
    - source /home/cyonexla/nodevenv/repositories/cyonex/24/bin/activate
    - npm ci
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R build/* $DEPLOYPATH